version: '3.8'

services:
  baladia-web-db-service:
    image: mysql:8.0
    container_name: mysql_baladia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: baladia-web
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
